### ISSUE TITLE
建议注明一下开源的数据是不能用到开源代码上面去的

### ISSUE THREAD

**Issue by bojone** [RowitZou/RankAE#1]
首先，开源代码是值得点赞的，感谢作者的工作；而在数据方面为了脱敏将文本转化为id也是可以理解的，纯id的数据在不用预训练模型的情况下也有一定的测试价值。

但是直接用开源的代码跑开源的数据是不会报错的，直接把id序列当成文本序列来处理了，这是非常有误导性的，建议注明一下：开源的代码需要用的是明文数据，而开源的数据是密文的，所以是不可用的，开源代码与数据是无法复现论文结果的，要想看效果需要自行准备明文数据。

**Comment by RowitZou** [comment]
Thanks for your suggestion! I have updated the README.md accordingly.
