### ISSUE TITLE
How use it?

### ISSUE THREAD

**Issue by leonardo-moraes-movile** [RowitZou/RankAE#2]
I have try to use your code in Google Colab, because I wasn't able to run in my machine due to specification.
Can you detail better how to use it? or even help me to create a trained sample on Google Colab?

**Comment by dengxingwang** [comment]
I need the help,too. Thanks!

**Comment by wallon-ai** [comment]
> I have try to use your code in Google Colab, because I wasn't able to run in my machine due to specification.
> Can you detail better how to use it? or even help me to create a trained sample on Google Colab?

I also need the help. Thanks!

**Comment by RowitZou** [comment]
The code was tested on Ubuntu with Nvidia Tesla V100 and it worked just fine. Could you please provide more details about your error log? The wrong data format might lead to preprocess failure. An example of your input data is also helpful for me to solve your problem.

**Comment by chostyouwang** [comment]
if you want to run, the machine require high level. when i operate the code on colab, in the process of  training , it occures runtime  errror: out of memory

**Comment by wallon-ai** [comment]
![image](https://user-images.githubusercontent.com/25277463/113081439-3f589e80-920b-11eb-8461-da603dde798a.png)
Hi, could you please tell me why the learning rate  is 0 when training? Thank you.

**Comment by RowitZou** [comment]
> ![image](https://user-images.githubusercontent.com/25277463/113081439-3f589e80-920b-11eb-8461-da603dde798a.png)
> Hi, could you please tell me why the learning rate is 0 when training? Thank you.

We use a warmup strategy in the pre-training process. The initial rate is 0 and increases when training continues. After a number of steps, it reaches the peak point and starts to decrease.
