### ISSUE TITLE
Train English model 

### ISSUE THREAD

**Issue by wallon-ai** [RowitZou/RankAE#3]
Hi, when I trained English  model I got the following error:  
![image](https://user-images.githubusercontent.com/25277463/114295530-68fda980-9ad8-11eb-98fb-8df37f572cfa.png)

I processed the data through the following command:  

python ./src/preprocess.py -raw_path json_data -save_path bert_data -bert_temp_dir bert/English_bert -log_file logs/preprocess.log

I can't figure out what went wrong.

**Comment by RowitZou** [comment]
The word index of processed input data is out of range. You can check the vocabulary size of BERT and the maximum index of input src_id, and make sure that all src_id indexes are in the range of BERT vocabulary size.
