### ISSUE TITLE
关于在16GB显存GPU上训练的疑问

### ISSUE THREAD

**Issue by HarborZeng** [RowitZou/RankAE#4]
感谢您的论文和开源此代码，我阅读了您的代码，您的代码写的非常工整严谨通俗易懂。

我使用了从qq导出的群聊记录，按照对话发生的时间分组，将数据打成了 sessions，当然我的聊天记录远远少于您的：

```bash
(RankAE) $ du -sh ks_bert_data/
59M	ks_bert_data/
(RankAE) $ du -sh bert_data/
6.6G	bert_data/
```

其中 `ks_bert_data` 是我准备的数据集经过 `preprocess.py` 脚本转化后的结果。

我的数据既然是群聊，就无角色之分，在您的代码中（src.models.rankae.RankAE._src_add_noise），我看到了被注释的几行，应该是您实验无角色训练的痕迹，于是我将那几行取消了注释，果然可以顺利训练。

我的 GPU 是 Quadro P5000 16G，我注意到您训练脚本的默认 `batch_size` 是 1600，而我的内存不足以支持这样的训练，于是将批次大小降低到了 64，才勉强支撑。

目前训练了 3 天，`tensorboard` log 展示如下

![image](https://user-images.githubusercontent.com/8568937/114332833-8e8ebf80-9b79-11eb-936c-d3a2cbd219b0.png)

以上，有3个疑问：

1. 我的数据量这么少，而且降低了批次大小，您觉得效果会达到我的预期么？
2. 您的论文和代码毕竟都是基于分角色数据集而来，无角色训练是否可行？
3. 依据您的经验，结合上图，此次训练还要持续多久才会收敛？

再次感谢您开源的代码，期待您为我解惑。

**Comment by RowitZou** [comment]
1. 训练参数中有两个批次大小，batch_size=1600 是指批次中对话的单词总数，batch_ex_size=2 是指批次对话个数。您首先需要确定 batch_size=64 是否真的可以包含大多数完整的对话。OOM 的问题可以靠多 GPU 来解决。预期效果与语言模型生成的质量有关，数据量少了之后，语言模型 PPL 如果降不下去，DAE 重构效果可能欠佳。

2. 角色之间的差异越大，角色信息的作用越明显。一般情况下，角色信息的加入能提高效果。您提到了群聊角色区分，是否可以设计如下形式：[r] + 角色名 + [/r] + utterance，[r] 与 [\r] 是特殊符号，相同角色的角色名在单个对话上下文中保持一致即可。

3. 已经接近收敛。

**Comment by HarborZeng** [comment]
感谢指点
