### ISSUE TITLE
数据长度是否有限制？

### ISSUE THREAD

**Issue by SCU-JJkinging** [RowitZou/RankAE#5]
请问下输入一个对话的json数据，它的总长度是否有限制呢？能否在较多轮次的对话中提取摘要呢？

**Comment by RowitZou** [comment]
参考preprocess.py 的参数设定，对话轮数默认最大为40，每轮词数默认最大为40。

理论上可以在较多轮次的对话中提取摘要，但是过长的对话可能会在训练阶段遇到OOM错误。

**Comment by SCU-JJkinging** [comment]
好的，感谢！

**Comment by SCU-JJkinging** [comment]
好的，感谢！

**Comment by SCU-JJkinging** [comment]
不好意思，还想请问下您的这些数据是怎么进行分词的呢？
![image](https://user-images.githubusercontent.com/59439162/139806143-47f20a12-2b04-428a-9414-0b5ea3288b59.png)
是直接用BertTokenizer吗？

**Comment by RowitZou** [comment]
使用 BertTokenizer

**Comment by SCU-JJkinging** [comment]
好的，再次感谢！
