### ISSUE TITLE
关于淘宝电商对话数据集的疑问

### ISSUE THREAD

**Issue by demeiyan** [RowitZou/RankAE#7]
我下载了你发布的淘宝电商电话数据集，但发现里面的content都是数字，我一开始以为是bert vocab对应的index但一对应发现也不对，后面读你预处理的代码发现应该是token，你那边有对这份数据集的说明吗？

![image](https://user-images.githubusercontent.com/12872156/158930645-d38504ef-643d-4d80-9420-136f186e9532.png)

debug发现你对数字进行tokenize，显然应该是原始文本，不知道你那边有没有对应的原文呢？

![image](https://user-images.githubusercontent.com/12872156/158930669-e61ca4aa-b424-4a64-861c-20c96bf9c116.png)

我怎么转成原文的文本呢？有没有对应关系啊，我想在你这个数据集上跑下效果

![image](https://user-images.githubusercontent.com/12872156/158932352-7dd3005f-8555-4d89-a3c4-d0f7fa6d98e1.png)

**Comment by RowitZou** [comment]
你好，因为数据敏感的原因，我们暂时无法公开原数据集。对此带来的不便表示歉意。您可以使用我们的代码在自己的对话数据集上尝试。
