### ISSUE TITLE
float下标的处理

### ISSUE THREAD

**Issue by seamoke** [RowitZou/RankAE#8]
您好，在代码/src/model/rankae.py:454处
```python
# Map beam_index to batch_index in the flat representation.
            batch_index = (
                    topk_beam_index
                    + beam_offset[:topk_beam_index.size(0)].unsqueeze(1))
            
            select_indices = batch_index.view(-1)
            # Append last prediction.
            alive_seq = torch.cat(
                [alive_seq.index_select(0, select_indices),
                 topk_ids.view(-1, 1)], -1)
```
batch_index出来是一个float类型，后续把它当作了对应的下标进行处理，请问这一步的转化在可运行的代码中是如何做的？直接强制转成int吗

**Comment by nihao517** [comment]
> 您好，在代码/src/model/rankae.py:454处
> 
> ```python
> # Map beam_index to batch_index in the flat representation.
>             batch_index = (
>                     topk_beam_index
>                     + beam_offset[:topk_beam_index.size(0)].unsqueeze(1))
>             
>             select_indices = batch_index.view(-1)
>             # Append last prediction.
>             alive_seq = torch.cat(
>                 [alive_seq.index_select(0, select_indices),
>                  topk_ids.view(-1, 1)], -1)
> ```
> 
> batch_index出来是一个float类型，后续把它当作了对应的下标进行处理，请问这一步的转化在可运行的代码中是如何做的？直接强制转成int吗

我也想问这个问题

**Comment by RowitZou** [comment]
你好，batch_index应为整型，这里数据类型错误可能是由于torch早期版本造成的。首先应当确保topk_beam_index是整型。
topk_beam_index = topk_ids.div(vocab_size) 的预期返回结果应当是topk_ids除以vocab_size的下取整。
